### ISSUE TITLE
Phone

### ISSUE THREAD

**Issue by milkina** [Arlick/Zimonin_O#8]
1. Добавить мод. доступа  переменным класса и методам.
2. Добавить сеттеры и геттеры.
3. Конструкторы пишутся сразу после объявления перемнных

**Comment by Arlick** [comment]
Исправил часть. добавил новое. Остальное добавлю позже.

**Comment by Arlick** [comment]
обавить мод. доступа переменным класса и методам.--- не понимаю что надо.
остальное подправил. залью позже
