### ISSUE TITLE
Инструменты

### ISSUE THREAD

**Issue by milkina** [Arlick/Zimonin_O#9]
1. musicInstrument, musicalInstrumentsDemo - пишите с большой буквы
2.  Добавить методы equals, toString
3. Drum, Trumpet - не отформатировано

**Comment by Arlick** [comment]
Добавить методы equals, toString
куда именно? В MusicInstrument, MusicalInstrumentsDemo? в остальных есть

**Comment by milkina** [comment]
Ой, недосмотрела. Пункт 2 не делаете
